apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ulgio0pp1-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ulgio0pp1-python 
  name: ulgio0pp1-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ulgio0pp1-python 
